### ISSUE TITLE
Unable to display gallery images in nexus v5.0.1

### ISSUE THREAD

**Issue by litao0621** [lovetuzitong/MultiImageSelector#3]
hi.
I tested some device .In the version 4.0-5.0  running well .when i use my nexus 5 (v5.0.1) open gallery can't display images

![Image](http://imglf0.ph.126.net/5U8aFDQecP9mav8RFKlgeg==/6630163967141088972.png)

**Comment by lovetuzitong** [comment]
@sd6352051 我这边也是N5额，表现ok的。试试从电脑导入一张图片到手机再看看？排除下是否是图片本就不存在。
ps. 之前用过你的库哇[NiftyDialogEffects](https://github.com/sd6352051/NiftyDialogEffects) :smile: 多多指教

**Comment by litao0621** [comment]
从电脑倒入的确实可以正常显示，但用手机拍照后的图却无法显示，很奇怪。
很不错的库，很棒 :+1:

**Comment by litao0621** [comment]
hi，我又发现一些导致这个问题的愿意，在使用5.0的相机时，左边栏可以选择一个镜头模糊，用这个拍照后好像图片就显示不出来了，但路径也没什么特别的，你可以试试
![Image](http://imglf0.ph.126.net/0z_74IWKbeEA_U9S4lqoBA==/6630740111234267034.png)

**Comment by ghost** [comment]
The image taken through camera is not displaying.
Device-  Moto E.
In other device its working fine

![screenshot_2015-04-22-15-55-32](https://cloud.githubusercontent.com/assets/6015930/7272454/93ce0836-e908-11e4-9ab7-4c359567637f.png)

Error in resizing of image at ImageGridAdapter.java 
     Picasso.with(mContext)
                        .load(imageFile)
                        .placeholder(R.drawable.default_error)
//                        .error(R.drawable.asy)
                        .resize(mItemSize, mItemSize)
                        .centerCrop()
                        .into(image);
SOLVED USING https://github.com/bumptech/glide as image loader instead of Picasso
![screenshot_2015-04-22-16-11-05](https://cloud.githubusercontent.com/assets/6015930/7272669/5c030ee0-e90a-11e4-8a71-37a6dabb1c4c.png)

Glide.with(mContext)
                        .load(imageFile)
                        .centerCrop()
                        .placeholder(R.drawable.default_error)
                        .crossFade()
                        .into(image);

**Comment by litao0621** [comment]
hi @mithrann  
worked well use glide.but  I don't want to change this lib in my project.
What method can be solved use Picasso?
or, do you have any good suggestions, tell me what to do
Thanks

**Comment by litao0621** [comment]
hi @lovetuzitong  看你更新了项目，你如果觉得提交到maven比较麻烦得话可以实用这个https://jitpack.io/ 前些天一个老外朋友推荐得，我觉得还不错：D

**Comment by lovetuzitong** [comment]
@sd6352051 谢啦，回头看看 :smile:

**Comment by qiuqiu3** [comment]
The issue is on Picasso side. 
This bug is fixed on master and you can try it with the 2.6.0-SNAPSHOT.
compile 'com.squareup.picasso:picasso:snapshot-2.6.0'
